/**
 * Known facts about the games that the built datasets must reproduce. Each one is something a
 * player can check in the game (or on Bulbapedia) and that the author is certain of; a failure
 * means the pipeline lost or invented data, not that the fact should be edited away.
 *
 * Species are national numbers, games are Pelagix ids.
 */
import type { EncounterKind, FormCategory } from '../../src/shared/dex-types.ts'

export type Fact =
  /** The form has a row of that kind in that game (optionally at a place, with a method, level, ...). */
  | {
      t: 'row'
      s: number
      f?: number
      game: string
      k: EncounterKind
      /** Text the location name contains. */
      at?: string
      /** Text the method label contains. */
      m?: string
      /** A level inside the row's range. */
      lv?: number
      shiny?: 'locked' | 'forced'
      ball?: number
      gender?: 0 | 1 | 2
      /** Text the note contains. */
      note?: string
      /** A condition the row lists. */
      c?: string
      via?: string
      rf?: true
      /** The Original Trainer name of the event row. */
      ot?: string
      /** Exactly this many rows of that kind (and level) in that game: one distribution, one row. */
      count?: number
    }
  /** The form has no row of that kind in that game (optionally: none with that method / at that place). */
  | { t: 'noRow'; s: number; f?: number; game: string; k: EncounterKind; m?: string; at?: string }
  /** The form is / is not obtainable without an event in that game. */
  | { t: 'obtain'; s: number; f?: number; game: string; yes: boolean }
  /** The form's only sources in that game are events. */
  | { t: 'eventOnly'; s: number; f?: number; game: string }
  /** The form evolves from `from` in that game, by a method whose text contains `how`. */
  | { t: 'evolve'; s: number; f?: number; from: [number, number]; game: string; how: string }
  /** The form cannot be evolved from `from` in that game (optionally: not by a method whose text contains `how`). */
  | { t: 'noEvolve'; s: number; f?: number; from: [number, number]; game: string; how?: string }
  | { t: 'breed'; s: number; f?: number; game: string; yes: boolean }
  | { t: 'present'; s: number; f?: number; game: string; yes: boolean }
  /** Properties of the form itself, whatever the game. */
  | { t: 'form'; s: number; f?: number; game?: undefined; cat?: FormCategory; full?: string; approx?: boolean; genderRate?: number }

export const FACTS: readonly Fact[] = [
  // --- Generation 1 ------------------------------------------------------------------------
  { t: 'row', s: 25, game: 'red', k: 'wild', at: 'Viridian Forest', lv: 3 },
  { t: 'row', s: 25, game: 'blue', k: 'wild', at: 'Power Plant' },
  { t: 'row', s: 25, game: 'yellow', k: 'gift', at: 'Pallet Town', m: 'Starter', lv: 5 },
  { t: 'noRow', s: 25, game: 'yellow', k: 'wild' },
  { t: 'row', s: 1, game: 'red', k: 'gift', at: 'Pallet Town', m: 'Starter', lv: 5 },
  { t: 'row', s: 1, game: 'yellow', k: 'gift', at: 'Cerulean City', lv: 10 },
  { t: 'row', s: 133, game: 'blue', k: 'gift', at: 'Celadon', lv: 25 },
  { t: 'row', s: 131, game: 'red', k: 'gift', at: 'Silph Co.', lv: 15 },
  { t: 'row', s: 150, game: 'yellow', k: 'static', at: 'Cerulean Cave', lv: 70 },
  { t: 'row', s: 143, game: 'red', k: 'static', at: 'Route 12', lv: 30 },
  { t: 'row', s: 143, game: 'red', k: 'static', at: 'Route 16', lv: 30 },
  { t: 'row', s: 137, game: 'red', k: 'gift', at: 'Game Corner', lv: 26 },
  { t: 'row', s: 137, game: 'blue', k: 'gift', at: 'Game Corner', lv: 18 },
  { t: 'row', s: 142, game: 'red', k: 'gift', at: 'Cinnabar', m: 'Fossil' },
  { t: 'obtain', s: 123, game: 'red', yes: true },
  { t: 'obtain', s: 123, game: 'blue', yes: false },
  { t: 'obtain', s: 127, game: 'blue', yes: true },
  { t: 'obtain', s: 127, game: 'red', yes: false },
  { t: 'obtain', s: 127, game: 'green', yes: true },
  { t: 'obtain', s: 123, game: 'green', yes: false },
  { t: 'obtain', s: 27, game: 'red', yes: false },
  { t: 'obtain', s: 23, game: 'blue', yes: false },
  { t: 'eventOnly', s: 151, game: 'red' },
  { t: 'row', s: 122, game: 'red', k: 'trade', at: 'Route 2', note: 'For an Abra' },
  { t: 'row', s: 68, game: 'yellow', k: 'trade', note: 'Evolves from Machoke' },
  { t: 'evolve', s: 65, from: [64, 0], game: 'red', how: 'Trade' },
  { t: 'evolve', s: 26, from: [25, 0], game: 'blue', how: 'Thunder Stone' },
  { t: 'breed', s: 133, game: 'red', yes: false },

  // --- Generation 2 ------------------------------------------------------------------------
  { t: 'row', s: 175, game: 'gold', k: 'egg', at: 'Violet City' },
  { t: 'row', s: 185, game: 'gold', k: 'static', at: 'Route 36' },
  { t: 'row', s: 130, game: 'silver', k: 'static', at: 'Lake of Rage', shiny: 'forced', lv: 30 },
  { t: 'row', s: 249, game: 'silver', k: 'static', at: 'Whirl Islands' },
  { t: 'row', s: 250, game: 'gold', k: 'static', at: 'Tin Tower' },
  { t: 'row', s: 201, f: 5, game: 'crystal', k: 'wild', at: 'Ruins of Alph', rf: true },
  { t: 'evolve', s: 196, from: [133, 0], game: 'gold', how: 'high friendship during the day' },
  { t: 'evolve', s: 197, from: [133, 0], game: 'crystal', how: 'high friendship at night' },
  { t: 'evolve', s: 208, from: [95, 0], game: 'silver', how: 'Trade holding a Metal Coat' },
  { t: 'evolve', s: 169, from: [42, 0], game: 'gold', how: 'Level up with high friendship' },
  { t: 'row', s: 95, game: 'gold', k: 'trade', at: 'Violet City', note: 'For a Bellsprout' },
  { t: 'row', s: 85, game: 'crystal', k: 'trade', at: 'Blackthorn City' },
  { t: 'noRow', s: 85, game: 'gold', k: 'trade' },
  { t: 'row', s: 112, game: 'gold', k: 'trade', at: 'Blackthorn City' },
  { t: 'breed', s: 172, game: 'gold', yes: true },
  { t: 'obtain', s: 172, game: 'silver', yes: true },
  { t: 'breed', s: 132, game: 'crystal', yes: false },

  // --- Generation 3 ------------------------------------------------------------------------
  { t: 'row', s: 252, game: 'ruby', k: 'gift', m: 'Starter', at: 'Route 101', lv: 5 },
  { t: 'row', s: 349, game: 'emerald', k: 'wild', at: 'Route 119', c: 'Feebas tiles' },
  { t: 'row', s: 384, game: 'sapphire', k: 'static', at: 'Sky Pillar', lv: 70 },
  { t: 'row', s: 25, game: 'ruby', k: 'wild', at: 'Safari Zone', ball: 5 },
  { t: 'row', s: 360, game: 'emerald', k: 'egg', at: 'Lavaridge Town' },
  { t: 'eventOnly', s: 151, game: 'emerald' },
  { t: 'row', s: 151, game: 'emerald', k: 'event', at: 'Faraway Island', note: 'Old Sea Map' },
  { t: 'eventOnly', s: 386, f: 1, game: 'firered' },
  { t: 'obtain', s: 270, game: 'sapphire', yes: true },
  { t: 'obtain', s: 270, game: 'ruby', yes: false },
  { t: 'row', s: 249, game: 'xd', k: 'shadow', at: 'Citadark Isle', lv: 50 },
  { t: 'row', s: 196, game: 'colosseum', k: 'gift', m: 'Starter', lv: 25 },
  { t: 'row', s: 131, game: 'firered', k: 'gift', at: 'Silph Co.' },
  { t: 'row', s: 201, f: 0, game: 'leafgreen', k: 'wild', at: 'Monean Chamber' },
  { t: 'evolve', s: 350, from: [349, 0], game: 'ruby', how: 'high Beauty' },
  { t: 'evolve', s: 292, from: [290, 0], game: 'emerald', how: 'empty party slot and a Poké Ball' },

  // --- Generation 4 ------------------------------------------------------------------------
  { t: 'row', s: 447, game: 'diamond', k: 'egg', at: 'Iron Island', note: 'Riley' },
  { t: 'row', s: 483, game: 'diamond', k: 'static', at: 'Spear Pillar', lv: 47 },
  { t: 'obtain', s: 484, game: 'diamond', yes: false },
  { t: 'obtain', s: 483, game: 'pearl', yes: false },
  { t: 'row', s: 487, f: 1, game: 'platinum', k: 'static', at: 'Distortion World' },
  { t: 'row', s: 442, game: 'pearl', k: 'static', at: 'Route 209', lv: 25 },
  { t: 'row', s: 446, game: 'diamond', k: 'wild', m: 'Honey Tree' },
  { t: 'row', s: 479, game: 'platinum', k: 'static', at: 'Old Chateau' },
  { t: 'eventOnly', s: 491, game: 'platinum' },
  { t: 'row', s: 25, game: 'heartgold', k: 'trade', at: 'Saffron City', note: 'Volty' },
  { t: 'row', s: 25, game: 'soulsilver', k: 'walker', m: 'Yellow Forest' },
  { t: 'row', s: 175, game: 'heartgold', k: 'egg', at: 'Violet City' },
  { t: 'evolve', s: 470, from: [133, 0], game: 'diamond', how: 'Moss Rock' },
  { t: 'evolve', s: 462, from: [82, 0], game: 'platinum', how: 'Magnetic Field' },
  { t: 'evolve', s: 461, from: [215, 0], game: 'pearl', how: 'holding a Razor Claw at night' },
  { t: 'evolve', s: 475, from: [281, 0], game: 'diamond', how: 'Dawn Stone on a male' },
  { t: 'breed', s: 447, game: 'diamond', yes: true },
  { t: 'present', s: 493, f: 9, game: 'diamond', yes: true },
  { t: 'present', s: 493, f: 17, game: 'diamond', yes: false },
  { t: 'present', s: 493, f: 17, game: 'x', yes: true },

  // --- Generation 5 ------------------------------------------------------------------------
  { t: 'eventOnly', s: 494, game: 'black' },
  { t: 'row', s: 643, game: 'black', k: 'static', lv: 50 },
  { t: 'obtain', s: 644, game: 'black', yes: false },
  { t: 'obtain', s: 643, game: 'white', yes: false },
  { t: 'row', s: 636, game: 'white', k: 'egg', at: 'Route 18' },
  { t: 'row', s: 646, game: 'black', k: 'static', at: 'Giant Chasm' },
  { t: 'row', s: 133, game: 'black2', k: 'wild', m: 'Hidden Grotto' },
  { t: 'row', s: 149, game: 'black2', k: 'wild', m: 'Hidden Grotto', at: 'Route 18' },
  { t: 'row', s: 55, game: 'white2', k: 'wild', m: 'Hidden Grotto', at: 'Abundant Shrine', lv: 37 },
  { t: 'row', s: 55, game: 'white2', k: 'wild', m: 'Hidden Grotto', at: 'Route 23', lv: 52 },
  { t: 'evolve', s: 589, from: [588, 0], game: 'black', how: 'Trade for a Shelmet' },
  { t: 'row', s: 25, game: 'black2', k: 'dream', m: 'Global Link promotion' },

  // --- Generation 6 ------------------------------------------------------------------------
  { t: 'row', s: 716, game: 'x', k: 'static', lv: 50 },
  { t: 'obtain', s: 717, game: 'x', yes: false },
  { t: 'obtain', s: 716, game: 'y', yes: false },
  { t: 'row', s: 656, game: 'y', k: 'gift', m: 'Starter', at: 'Aquacorde Town' },
  { t: 'row', s: 25, game: 'x', k: 'wild', m: 'Friend Safari' },
  { t: 'row', s: 25, game: 'omegaruby', k: 'gift', note: 'Cosplay Pikachu' },
  { t: 'present', s: 25, f: 1, game: 'omegaruby', yes: false },
  { t: 'evolve', s: 687, from: [686, 0], game: 'x', how: 'upside down' },
  { t: 'evolve', s: 700, from: [133, 0], game: 'y', how: 'high affection knowing a Fairy-type move' },
  { t: 'evolve', s: 675, from: [674, 0], game: 'x', how: 'Dark-type Pokémon in the party' },
  { t: 'row', s: 384, game: 'alphasapphire', k: 'static', at: 'Sky Pillar' },

  // --- Generation 7 ------------------------------------------------------------------------
  { t: 'row', s: 722, game: 'sun', k: 'gift', m: 'Starter' },
  { t: 'evolve', s: 791, from: [790, 0], game: 'sun', how: 'Level 53' },
  { t: 'noEvolve', s: 792, from: [790, 0], game: 'sun' },
  { t: 'evolve', s: 792, from: [790, 0], game: 'ultramoon', how: 'Level 53' },
  { t: 'evolve', s: 26, f: 1, from: [25, 0], game: 'moon', how: 'Thunder Stone' },
  { t: 'noEvolve', s: 26, f: 0, from: [25, 0], game: 'moon' },
  { t: 'evolve', s: 26, f: 0, from: [25, 0], game: 'ultrasun', how: 'in Ultra Space' },
  { t: 'row', s: 785, game: 'sun', k: 'static', at: 'Ruins of Conflict', shiny: 'locked' },
  { t: 'row', s: 778, game: 'moon', k: 'wild', at: 'Thrifty Megamart' },
  { t: 'row', s: 25, f: 8, game: 'letsgopikachu', k: 'gift', m: 'Starter' },
  { t: 'present', s: 25, f: 8, game: 'letsgoeevee', yes: true },
  { t: 'noRow', s: 25, f: 8, game: 'letsgoeevee', k: 'gift' },
  { t: 'row', s: 150, game: 'letsgoeevee', k: 'static', at: 'Cerulean Cave' },
  { t: 'breed', s: 133, game: 'letsgoeevee', yes: false },

  // --- Generation 8 ------------------------------------------------------------------------
  { t: 'row', s: 810, game: 'sword', k: 'gift', m: 'Starter', at: 'Postwick' },
  { t: 'row', s: 888, game: 'sword', k: 'static', shiny: 'locked' },
  { t: 'obtain', s: 889, game: 'sword', yes: false },
  { t: 'obtain', s: 888, game: 'shield', yes: false },
  { t: 'row', s: 25, game: 'sword', k: 'gift', at: 'Wild Area Station', note: 'Gigantamax', shiny: 'locked' },
  { t: 'row', s: 150, game: 'shield', k: 'raid', m: 'Dynamax Adventure', at: 'Max Lair' },
  { t: 'evolve', s: 865, from: [83, 1], game: 'sword', how: 'three critical hits' },
  { t: 'evolve', s: 849, f: 1, from: [848, 0], game: 'shield', how: 'Level 30' },
  { t: 'evolve', s: 869, from: [868, 0], game: 'sword', how: 'Spin' },
  { t: 'evolve', s: 892, from: [891, 0], game: 'sword', how: 'Tower of Darkness' },
  { t: 'row', s: 151, game: 'brilliantdiamond', k: 'gift', at: 'Floaroma Town' },
  { t: 'row', s: 493, game: 'shiningpearl', k: 'static', at: 'Hall of Origin' },
  { t: 'eventOnly', s: 491, game: 'brilliantdiamond' },
  { t: 'row', s: 722, game: 'legendsarceus', k: 'gift', m: 'Starter' },
  { t: 'row', s: 493, game: 'legendsarceus', k: 'static', at: 'Temple of Sinnoh', ball: 28 },
  { t: 'row', s: 25, game: 'legendsarceus', k: 'wild', at: "Nature's Pantry", c: 'Alpha' },
  { t: 'evolve', s: 901, from: [217, 0], game: 'legendsarceus', how: 'Peat Block under a full moon' },
  { t: 'evolve', s: 899, from: [234, 0], game: 'legendsarceus', how: 'Psyshield Bash' },
  { t: 'breed', s: 172, game: 'legendsarceus', yes: false },

  // --- Generation 9 ------------------------------------------------------------------------
  { t: 'row', s: 906, game: 'scarlet', k: 'gift', m: 'Starter', at: 'Cabo Poco', shiny: 'locked' },
  { t: 'obtain', s: 1007, game: 'scarlet', yes: true },
  { t: 'obtain', s: 1007, game: 'violet', yes: false },
  { t: 'obtain', s: 1008, game: 'scarlet', yes: false },
  { t: 'row', s: 246, game: 'scarlet', k: 'wild' },
  { t: 'noRow', s: 246, game: 'violet', k: 'wild' },
  { t: 'noRow', s: 246, game: 'violet', k: 'outbreak' },
  { t: 'row', s: 371, game: 'violet', k: 'wild' },
  { t: 'noRow', s: 371, game: 'scarlet', k: 'wild' },
  { t: 'row', s: 128, f: 2, game: 'scarlet', k: 'wild' },
  { t: 'noRow', s: 128, f: 2, game: 'violet', k: 'wild' },
  { t: 'row', s: 128, f: 1, game: 'violet', k: 'wild' },
  { t: 'row', s: 935, game: 'violet', k: 'wild' },
  { t: 'row', s: 984, game: 'scarlet', k: 'wild', at: 'Area Zero' },
  { t: 'obtain', s: 984, game: 'violet', yes: false },
  { t: 'obtain', s: 990, game: 'scarlet', yes: false },
  { t: 'evolve', s: 936, from: [935, 0], game: 'scarlet', how: 'Auspicious Armor' },
  { t: 'noEvolve', s: 936, from: [935, 0], game: 'violet' },
  { t: 'evolve', s: 1000, from: [999, 0], game: 'violet', how: '999 Gimmighoul Coins' },
  { t: 'evolve', s: 964, from: [963, 0], game: 'scarlet', how: 'Union Circle' },
  { t: 'row', s: 1017, game: 'scarlet', k: 'static', at: 'Dreaded Den', shiny: 'locked', gender: 1 },
  { t: 'row', s: 6, game: 'violet', k: 'tera', m: '7★ Tera Raid' },
  { t: 'row', s: 152, game: 'legendsza', k: 'gift', m: 'Starter' },
  { t: 'row', s: 670, f: 5, game: 'legendsza', k: 'gift', shiny: 'locked' },
  { t: 'row', s: 25, game: 'legendsza', k: 'wild', m: 'Wild Zone', at: 'Wild Zone 3' },

  // --- services and events -----------------------------------------------------------------------
  { t: 'row', s: 25, game: 'go', k: 'wild', m: 'Pokémon GO', via: 'go' },
  { t: 'obtain', s: 808, game: 'go', yes: true },
  { t: 'eventOnly', s: 893, f: 1, game: 'sword' },
  { t: 'row', s: 490, game: 'diamond', k: 'event', via: 'ranger' },
  { t: 'row', s: 1, game: 'red', k: 'event', via: 'stadium' },
  { t: 'row', s: 263, game: 'emerald', k: 'event', via: 'boxrubysapphire', c: 'Egg' },

  // --- regressions: defects the dataset verifiers found (October 2026) --------------------------------
  // Headbutt only where there are trees; Abra's Gold / Silver Headbutt group is unused.
  { t: 'noRow', s: 63, game: 'gold', k: 'wild', m: 'Headbutt' },
  { t: 'noRow', s: 48, game: 'silver', k: 'wild', m: 'Headbutt' },
  { t: 'noRow', s: 214, game: 'crystal', k: 'wild', at: 'Route 45' },
  { t: 'row', s: 214, game: 'crystal', k: 'wild', m: 'Headbutt', at: 'Azalea Town' },
  { t: 'row', s: 63, game: 'gold', k: 'wild', at: 'Route 34' },
  // Fossils are version-bound where the game only has some of them.
  { t: 'obtain', s: 408, game: 'diamond', yes: true },
  { t: 'obtain', s: 408, game: 'pearl', yes: false },
  { t: 'obtain', s: 410, game: 'pearl', yes: true },
  { t: 'obtain', s: 410, game: 'diamond', yes: false },
  { t: 'obtain', s: 411, game: 'diamond', yes: false },
  { t: 'obtain', s: 408, game: 'platinum', yes: true },
  { t: 'obtain', s: 410, game: 'platinum', yes: true },
  { t: 'obtain', s: 138, game: 'heartgold', yes: true },
  { t: 'obtain', s: 138, game: 'soulsilver', yes: false },
  { t: 'obtain', s: 140, game: 'soulsilver', yes: true },
  { t: 'obtain', s: 140, game: 'heartgold', yes: false },
  { t: 'obtain', s: 347, game: 'heartgold', yes: true },
  { t: 'obtain', s: 345, game: 'heartgold', yes: false },
  { t: 'obtain', s: 408, game: 'heartgold', yes: false },
  { t: 'obtain', s: 410, game: 'soulsilver', yes: false },
  { t: 'obtain', s: 142, game: 'heartgold', yes: true },
  { t: 'obtain', s: 345, game: 'x', yes: true },
  { t: 'obtain', s: 345, game: 'y', yes: false },
  { t: 'obtain', s: 138, game: 'y', yes: true },
  { t: 'obtain', s: 138, game: 'x', yes: false },
  { t: 'obtain', s: 696, game: 'x', yes: true },
  { t: 'obtain', s: 140, game: 'omegaruby', yes: true },
  { t: 'obtain', s: 140, game: 'alphasapphire', yes: false },
  { t: 'obtain', s: 408, game: 'alphasapphire', yes: true },
  { t: 'obtain', s: 408, game: 'omegaruby', yes: false },
  { t: 'obtain', s: 696, game: 'omegaruby', yes: false },
  { t: 'obtain', s: 345, game: 'omegaruby', yes: true },
  { t: 'obtain', s: 408, game: 'sun', yes: true },
  { t: 'obtain', s: 408, game: 'moon', yes: false },
  { t: 'obtain', s: 566, game: 'moon', yes: true },
  { t: 'obtain', s: 566, game: 'sun', yes: false },
  { t: 'obtain', s: 138, game: 'sun', yes: false },
  { t: 'obtain', s: 139, game: 'moon', yes: false },
  { t: 'obtain', s: 696, game: 'moon', yes: false },
  { t: 'obtain', s: 138, game: 'ultrasun', yes: true },
  { t: 'obtain', s: 138, game: 'ultramoon', yes: true },
  { t: 'row', s: 142, game: 'sun', k: 'gift', m: 'Gift', at: 'Seafolk Village' },
  { t: 'obtain', s: 408, game: 'brilliantdiamond', yes: true },
  { t: 'obtain', s: 408, game: 'shiningpearl', yes: false },
  { t: 'obtain', s: 410, game: 'brilliantdiamond', yes: false },
  // Dynamax Crystal dens are serial-code distributions.
  { t: 'obtain', s: 782, game: 'shield', yes: false },
  { t: 'obtain', s: 784, game: 'shield', yes: false },
  { t: 'obtain', s: 782, game: 'sword', yes: true },
  { t: 'obtain', s: 246, game: 'sword', yes: false },
  { t: 'obtain', s: 248, game: 'sword', yes: false },
  { t: 'obtain', s: 874, game: 'shield', yes: false },
  { t: 'obtain', s: 875, game: 'sword', yes: false },
  { t: 'eventOnly', s: 782, game: 'shield' },
  { t: 'row', s: 246, game: 'sword', k: 'raid', m: 'Dynamax Crystal den', at: 'Watchtower Ruins' },
  // Global Link promotions were campaigns with an end date.
  { t: 'eventOnly', s: 493, game: 'black' },
  { t: 'eventOnly', s: 384, game: 'white' },
  { t: 'row', s: 493, game: 'black', k: 'dream', m: 'Global Link promotion', at: 'Entree Forest' },
  { t: 'obtain', s: 387, game: 'black2', yes: false },
  { t: 'row', s: 138, game: 'black', k: 'dream', m: 'Dream World' },
  // Platinum's Regi ruins need the distributed Regigigas.
  { t: 'eventOnly', s: 377, game: 'platinum' },
  { t: 'eventOnly', s: 378, game: 'platinum' },
  { t: 'eventOnly', s: 379, game: 'platinum' },
  { t: 'row', s: 377, game: 'platinum', k: 'event', at: 'Rock Peak Ruins', note: 'Regigigas' },
  // Event-only Pokéwalker courses.
  { t: 'obtain', s: 52, game: 'heartgold', yes: false },
  { t: 'obtain', s: 53, game: 'heartgold', yes: false },
  { t: 'obtain', s: 52, game: 'soulsilver', yes: true },
  { t: 'obtain', s: 302, game: 'soulsilver', yes: false },
  { t: 'obtain', s: 302, game: 'heartgold', yes: true },
  { t: 'eventOnly', s: 52, game: 'heartgold' },
  { t: 'row', s: 52, game: 'heartgold', k: 'walker', m: 'Sightseeing', note: 'distributed' },
  // Yellow's partner Pikachu will not evolve.
  { t: 'obtain', s: 26, game: 'yellow', yes: false },
  { t: 'noEvolve', s: 26, from: [25, 0], game: 'yellow' },
  { t: 'obtain', s: 26, game: 'red', yes: true },
  // Evolution texts.
  { t: 'evolve', s: 706, from: [705, 0], game: 'x', how: 'while it is raining' },
  { t: 'evolve', s: 706, from: [705, 0], game: 'alphasapphire', how: 'while it is raining' },
  { t: 'evolve', s: 706, from: [705, 0], game: 'sun', how: 'rain or fog' },
  { t: 'evolve', s: 892, from: [891, 0], game: 'scarlet', how: 'Scroll of Darkness' },
  { t: 'noEvolve', s: 892, from: [891, 0], game: 'scarlet', how: 'Tower' },
  { t: 'noEvolve', s: 892, f: 1, from: [891, 0], game: 'violet', how: 'Tower' },
  { t: 'evolve', s: 892, f: 1, from: [891, 0], game: 'shield', how: 'Tower of Waters' },
  { t: 'evolve', s: 745, f: 2, from: [744, 1], game: 'ultrasun', how: '5:00-5:59 PM' },
  { t: 'evolve', s: 745, f: 2, from: [744, 1], game: 'sword', how: '7:00-7:59 PM' },
  { t: 'evolve', s: 745, f: 2, from: [744, 1], game: 'scarlet', how: 'in the evening' },
  { t: 'noEvolve', s: 745, f: 2, from: [744, 1], game: 'scarlet', how: 'PM' },
  { t: 'evolve', s: 350, from: [349, 0], game: 'black', how: 'Prism Scale' },
  { t: 'noEvolve', s: 350, from: [349, 0], game: 'black', how: 'Beauty' },
  { t: 'noEvolve', s: 350, from: [349, 0], game: 'sword', how: 'Beauty' },
  { t: 'noEvolve', s: 350, from: [349, 0], game: 'legendsza', how: 'Beauty' },
  { t: 'evolve', s: 350, from: [349, 0], game: 'heartgold', how: 'high Beauty' },
  { t: 'evolve', s: 350, from: [349, 0], game: 'brilliantdiamond', how: 'high Beauty' },
  // Version-bound evolution items.
  { t: 'obtain', s: 841, game: 'sword', yes: true },
  { t: 'obtain', s: 841, game: 'shield', yes: false },
  { t: 'obtain', s: 842, game: 'sword', yes: false },
  { t: 'noEvolve', s: 842, from: [840, 0], game: 'sword' },
  { t: 'evolve', s: 842, from: [840, 0], game: 'shield', how: 'Sweet Apple' },
  { t: 'evolve', s: 841, from: [840, 0], game: 'violet', how: 'Tart Apple' },
  // Evolutions a game has no place or clock for.
  { t: 'noEvolve', s: 462, from: [82, 0], game: 'heartgold' },
  { t: 'obtain', s: 462, game: 'soulsilver', yes: false },
  { t: 'noEvolve', s: 476, from: [299, 0], game: 'heartgold' },
  { t: 'noEvolve', s: 470, from: [133, 0], game: 'soulsilver' },
  { t: 'noEvolve', s: 471, from: [133, 0], game: 'heartgold' },
  { t: 'obtain', s: 471, game: 'heartgold', yes: false },
  { t: 'noEvolve', s: 196, from: [133, 0], game: 'firered' },
  { t: 'noEvolve', s: 197, from: [133, 0], game: 'leafgreen' },
  { t: 'obtain', s: 196, game: 'firered', yes: false },
  { t: 'evolve', s: 196, from: [133, 0], game: 'xd', how: 'Sun Shard' },
  { t: 'evolve', s: 197, from: [133, 0], game: 'xd', how: 'Moon Shard' },
  { t: 'evolve', s: 196, from: [133, 0], game: 'emerald', how: 'high friendship during the day' },
  // Hoenn outbreaks belong to the game that generates them.
  { t: 'obtain', s: 273, game: 'sapphire', yes: false },
  { t: 'obtain', s: 275, game: 'sapphire', yes: false },
  { t: 'obtain', s: 273, game: 'ruby', yes: true },
  { t: 'obtain', s: 283, game: 'emerald', yes: false },
  { t: 'row', s: 283, game: 'sapphire', k: 'wild', m: 'Swarm', at: 'Route 102' },
  { t: 'row', s: 273, game: 'emerald', k: 'wild', m: 'Swarm', at: 'Route 120', lv: 25 },
  { t: 'noRow', s: 273, game: 'ruby', k: 'wild', m: 'Swarm' },
  { t: 'row', s: 300, game: 'emerald', k: 'wild', m: 'Swarm', lv: 8 },
  // Crystal has no reachable Remoraid.
  { t: 'obtain', s: 223, game: 'crystal', yes: false },
  { t: 'obtain', s: 224, game: 'crystal', yes: false },
  { t: 'obtain', s: 223, game: 'gold', yes: true },
  // Game Corner prizes carry one label in every generation, in the version that offers them.
  { t: 'row', s: 147, game: 'gold', k: 'gift', m: 'Game Corner prize', at: 'Goldenrod City (Game Corner)', lv: 10 },
  { t: 'row', s: 63, game: 'firered', k: 'gift', m: 'Game Corner prize', at: 'Celadon City (Game Corner)', lv: 9 },
  { t: 'row', s: 246, game: 'crystal', k: 'gift', m: 'Game Corner prize', lv: 40 },
  { t: 'row', s: 137, game: 'soulsilver', k: 'gift', m: 'Game Corner prize', at: 'Celadon City (Game Corner)' },
  { t: 'row', s: 23, game: 'gold', k: 'gift', m: 'Game Corner prize' },
  { t: 'noRow', s: 23, game: 'silver', k: 'gift' },
  { t: 'noRow', s: 27, game: 'gold', k: 'gift' },
  { t: 'row', s: 133, game: 'gold', k: 'gift', m: 'Gift', at: 'Goldenrod City', lv: 20 },
  // Island Scan.
  { t: 'row', s: 158, game: 'sun', k: 'static', m: 'Island Scan', at: 'Seaward Cave', c: 'Monday' },
  { t: 'row', s: 4, game: 'ultramoon', k: 'static', m: 'Island Scan', at: 'Route 3', c: 'Sunday' },
  { t: 'row', s: 479, game: 'ultrasun', k: 'static', m: 'Island Scan', c: 'Tuesday' },
  // N's Zorua is handed over; his other Pokémon are met in the wild.
  { t: 'row', s: 570, game: 'black2', k: 'gift', at: 'Driftveil City', note: "N's Pokémon" },
  { t: 'noRow', s: 570, game: 'black2', k: 'static' },
  { t: 'row', s: 509, game: 'white2', k: 'static', m: "N's Pokémon" },
  // Requirements worth a note.
  { t: 'row', s: 719, game: 'legendsza', k: 'static', note: 'Diancite' },
  { t: 'row', s: 251, game: 'crystal', k: 'static', at: 'Ilex Forest', note: 'GS Ball' },
  // Pokémon GO has Pokémon that cannot leave it.
  { t: 'obtain', s: 327, game: 'go', yes: true },
  { t: 'obtain', s: 718, game: 'go', yes: true },
  { t: 'row', s: 327, game: 'go', k: 'wild', via: 'go', note: 'Cannot be sent to Pokémon HOME' },
  // Eggs hatch in the base state.
  { t: 'breed', s: 479, f: 1, game: 'black', yes: false },
  { t: 'breed', s: 351, f: 1, game: 'white2', yes: false },
  { t: 'breed', s: 479, game: 'black', yes: true },
  { t: 'breed', s: 412, f: 1, game: 'diamond', yes: true },
  // Ambushes, caves, swarms, spots and Hisuian place names.
  { t: 'row', s: 527, game: 'x', k: 'wild', m: 'Ambush', at: 'Glittering Cave' },
  { t: 'row', s: 227, game: 'y', k: 'wild', m: 'Ambush', at: 'Victory Road' },
  { t: 'row', s: 41, game: 'ruby', k: 'wild', m: 'Cave', at: 'Meteor Falls' },
  { t: 'row', s: 41, game: 'diamond', k: 'wild', m: 'Cave', at: 'Ravaged Path' },
  { t: 'row', s: 41, game: 'platinum', k: 'wild', m: 'Cave', at: 'Iron Island' },
  { t: 'row', s: 41, game: 'gold', k: 'wild', m: 'Cave', at: 'Tohjo Falls' },
  { t: 'row', s: 211, game: 'gold', k: 'wild', m: 'Old Rod', at: 'Route 32', c: 'Swarm', lv: 5 },
  { t: 'row', s: 211, game: 'crystal', k: 'wild', m: 'Super Rod', at: 'Route 32', c: 'Swarm', lv: 40 },
  { t: 'noRow', s: 211, game: 'gold', k: 'static' },
  { t: 'row', s: 223, game: 'silver', k: 'wild', m: 'Good Rod', at: 'Route 44', c: 'Swarm', lv: 20 },
  { t: 'row', s: 100, game: 'xd', k: 'shadow', at: 'Cave Poké Spot' },
  { t: 'row', s: 299, game: 'xd', k: 'shadow', at: 'Rock Poké Spot' },
  { t: 'row', s: 46, game: 'legendsarceus', k: 'static', at: "Nature's Pantry (Obsidian Fieldlands)" },
  // Distributions: one row each, English title and OT, the games that could receive them.
  { t: 'row', s: 485, game: 'ultramoon', k: 'event', note: 'Sizzling Heatran!', ot: '2018 Legends', lv: 100 },
  { t: 'row', s: 792, game: 'ultrasun', k: 'event', note: 'Radiant Lunala', ot: 'Eclipse' },
  { t: 'row', s: 25, game: 'omegaruby', k: 'event', note: 'The Pikachu Cup Is a Go!' },
  { t: 'row', s: 666, f: 19, game: 'x', k: 'event', note: "It's a Poké Ball Pattern Vivillon!" },
  { t: 'row', s: 492, game: 'diamond', k: 'event', note: 'Meet SHAYMIN!' },
  { t: 'row', s: 491, game: 'pearl', k: 'event', note: 'The Rise of Darkrai', ot: 'ALAMOS' },
  { t: 'row', s: 25, f: 7, game: 'ultrasun', k: 'event', lv: 21, ot: 'Ash', count: 1 },
  { t: 'row', s: 724, game: 'sun', k: 'event', lv: 50, note: 'Pokémon Bank', count: 1 },
  { t: 'row', s: 386, game: 'diamond', k: 'event', m: 'Pokémon Ranger', via: 'ranger', ot: 'Oblivia', note: 'Deoxys gift' },
  { t: 'row', s: 491, game: 'heartgold', k: 'event', m: 'Pokémon Ranger', via: 'ranger', ot: 'Almia' },
  { t: 'row', s: 1, game: 'sword', k: 'event', lv: 14, via: 'home', count: 1 },
  { t: 'row', s: 1, game: 'emerald', k: 'event', lv: 70, ot: '10 ANIV' },
  { t: 'row', s: 1, game: 'leafgreen', k: 'event', lv: 70, ot: '10 ANIV' },
  { t: 'row', s: 6, game: 'sapphire', k: 'event', lv: 70, count: 1 },
  { t: 'row', s: 385, game: 'sapphire', k: 'event', m: 'Bonus Disc', via: 'colosseum', ot: 'WISHMKR' },
  { t: 'row', s: 263, game: 'ruby', k: 'event', m: 'Berry Glitch fix', ot: 'RUBY', shiny: 'forced' },
  { t: 'row', s: 263, game: 'sapphire', k: 'event', m: 'Berry Glitch fix', ot: 'SAPHIRE', shiny: 'forced' },
  { t: 'row', s: 83, game: 'crystal', k: 'event', via: 'stadium2', count: 1 },
  // What evolves or hatches from an event-only Pokémon is event-only too.
  { t: 'eventOnly', s: 2, game: 'gold' },
  { t: 'eventOnly', s: 3, game: 'ruby' },
  { t: 'eventOnly', s: 745, f: 2, game: 'ultrasun' },
  { t: 'eventOnly', s: 489, game: 'platinum' },
  { t: 'eventOnly', s: 489, game: 'brilliantdiamond' },
  { t: 'obtain', s: 489, game: 'legendsarceus', yes: true },
  // Forms reached by an in-game form change, and base forms reached from the changed one.
  { t: 'obtain', s: 492, f: 1, game: 'legendsarceus', yes: true },
  { t: 'eventOnly', s: 492, f: 1, game: 'platinum' },
  { t: 'evolve', s: 492, f: 1, from: [492, 0], game: 'legendsarceus', how: 'Gracidea' },
  { t: 'obtain', s: 483, f: 1, game: 'legendsarceus', yes: true },
  { t: 'obtain', s: 484, f: 1, game: 'legendsarceus', yes: true },
  { t: 'obtain', s: 487, game: 'legendsarceus', yes: true },
  { t: 'evolve', s: 487, from: [487, 1], game: 'legendsarceus', how: 'Griseous Core' },
  { t: 'obtain', s: 487, f: 1, game: 'black2', yes: true },
  { t: 'obtain', s: 487, f: 1, game: 'brilliantdiamond', yes: true },
  { t: 'obtain', s: 493, f: 9, game: 'legendsarceus', yes: true },
  { t: 'obtain', s: 493, f: 1, game: 'shiningpearl', yes: true },
  { t: 'obtain', s: 646, f: 1, game: 'white2', yes: true },
  { t: 'obtain', s: 646, f: 1, game: 'black2', yes: false },
  { t: 'obtain', s: 646, f: 2, game: 'black2', yes: true },
  { t: 'obtain', s: 646, f: 1, game: 'sword', yes: true },
  { t: 'obtain', s: 646, f: 2, game: 'sword', yes: false },
  { t: 'obtain', s: 646, f: 1, game: 'scarlet', yes: true },
  { t: 'obtain', s: 646, f: 1, game: 'violet', yes: false },
  { t: 'obtain', s: 646, f: 1, game: 'x', yes: false },
  // The partner has to be in the same game: each version's Max Lair and Snacksworth have their own legendaries.
  { t: 'obtain', s: 643, game: 'sword', yes: true },
  { t: 'obtain', s: 643, game: 'shield', yes: false },
  { t: 'obtain', s: 644, game: 'sword', yes: false },
  { t: 'obtain', s: 249, game: 'sword', yes: false },
  { t: 'obtain', s: 716, game: 'shield', yes: false },
  { t: 'obtain', s: 150, game: 'sword', yes: true },
  { t: 'obtain', s: 150, game: 'shield', yes: true },
  { t: 'obtain', s: 643, game: 'scarlet', yes: true },
  { t: 'obtain', s: 643, game: 'violet', yes: false },
  { t: 'obtain', s: 640, game: 'scarlet', yes: false },
  { t: 'obtain', s: 897, game: 'violet', yes: true },
  { t: 'obtain', s: 897, game: 'scarlet', yes: false },
  { t: 'obtain', s: 144, game: 'scarlet', yes: true },
  { t: 'obtain', s: 144, game: 'violet', yes: true },
  { t: 'obtain', s: 646, game: 'violet', yes: true },
  { t: 'obtain', s: 800, f: 1, game: 'scarlet', yes: true },
  { t: 'obtain', s: 800, f: 1, game: 'violet', yes: false },
  { t: 'obtain', s: 800, f: 2, game: 'sword', yes: false },
  { t: 'obtain', s: 800, f: 1, game: 'ultrasun', yes: true },
  { t: 'obtain', s: 800, f: 1, game: 'ultramoon', yes: false },
  { t: 'obtain', s: 800, f: 2, game: 'shield', yes: true },
  { t: 'obtain', s: 898, f: 1, game: 'sword', yes: true },
  { t: 'obtain', s: 898, f: 2, game: 'shield', yes: true },
  { t: 'evolve', s: 898, f: 2, from: [898, 0], game: 'sword', how: 'Fuse with Spectrier' },
  { t: 'obtain', s: 773, f: 9, game: 'sun', yes: true },
  { t: 'obtain', s: 773, f: 17, game: 'shield', yes: true },
  { t: 'obtain', s: 676, f: 1, game: 'x', yes: true },
  { t: 'obtain', s: 676, f: 9, game: 'legendsza', yes: true },
  { t: 'obtain', s: 1017, f: 1, game: 'scarlet', yes: true },
  { t: 'obtain', s: 1017, f: 3, game: 'violet', yes: true },
  { t: 'obtain', s: 479, f: 1, game: 'black', yes: true },
  { t: 'obtain', s: 479, f: 2, game: 'scarlet', yes: true },
  { t: 'obtain', s: 479, f: 3, game: 'brilliantdiamond', yes: true },
  { t: 'eventOnly', s: 479, f: 1, game: 'platinum' },
  { t: 'evolve', s: 479, f: 1, from: [479, 0], game: 'platinum', how: 'Secret Key' },
  { t: 'obtain', s: 386, f: 1, game: 'omegaruby', yes: true },
  { t: 'eventOnly', s: 386, f: 1, game: 'firered' },
  { t: 'obtain', s: 386, f: 2, game: 'firered', yes: false },
  // A Generation 3 Deoxys has the forme of its cartridge, however it was distributed.
  { t: 'row', s: 386, game: 'ruby', k: 'event', ot: 'SPACE C', lv: 70 },
  { t: 'row', s: 386, f: 1, game: 'firered', k: 'event', ot: 'SPACE C', lv: 70, note: 'Attack Deoxys gift' },
  { t: 'row', s: 386, f: 3, game: 'emerald', k: 'event', ot: 'DOEL' },
  { t: 'noRow', s: 386, game: 'firered', k: 'event' },
  { t: 'obtain', s: 647, game: 'sword', yes: true },
  { t: 'evolve', s: 647, from: [647, 1], game: 'shield', how: 'forget Secret Sword' },
  { t: 'obtain', s: 641, game: 'black2', yes: true },
  { t: 'obtain', s: 642, game: 'white2', yes: true },
  { t: 'obtain', s: 645, game: 'black2', yes: true },
  { t: 'obtain', s: 641, f: 1, game: 'legendsarceus', yes: true },
  { t: 'obtain', s: 905, f: 1, game: 'legendsarceus', yes: true },
  { t: 'obtain', s: 720, f: 1, game: 'legendsza', yes: true },
  { t: 'obtain', s: 649, f: 1, game: 'legendsza', yes: true },
  { t: 'obtain', s: 412, f: 1, game: 'diamond', yes: true },
  { t: 'obtain', s: 412, f: 2, game: 'x', yes: true },
  { t: 'obtain', s: 413, f: 1, game: 'diamond', yes: true },
  { t: 'obtain', s: 413, f: 2, game: 'heartgold', yes: true },
  { t: 'obtain', s: 413, f: 1, game: 'omegaruby', yes: false },
  // Zygarde: Power Construct is not a look; the 10% and 50% Formes are had through it.
  { t: 'form', s: 718, f: 2, cat: 'hidden' },
  { t: 'form', s: 718, f: 3, cat: 'hidden' },
  { t: 'form', s: 718, f: 1, cat: 'changeable' },
  { t: 'obtain', s: 718, game: 'legendsza', yes: true },
  { t: 'obtain', s: 718, f: 1, game: 'legendsza', yes: true },
  { t: 'obtain', s: 718, game: 'sword', yes: true },
  { t: 'obtain', s: 718, f: 1, game: 'shield', yes: true },
  { t: 'row', s: 718, game: 'sword', k: 'raid', m: 'Dynamax Adventure', note: 'Power Construct' },
  { t: 'row', s: 718, f: 1, game: 'legendsza', k: 'static', at: 'Wild Zone 20', note: 'Power Construct' },
  { t: 'evolve', s: 718, from: [718, 1], game: 'legendsza', how: 'Zygarde Cube' },
  // Vivillon: only the patterns a game really has, and never from a hidden form.
  { t: 'obtain', s: 666, game: 'legendsza', yes: false },
  { t: 'obtain', s: 666, f: 6, game: 'legendsza', yes: true },
  { t: 'obtain', s: 666, f: 8, game: 'legendsza', yes: true },
  { t: 'obtain', s: 666, f: 1, game: 'legendsza', yes: false },
  { t: 'obtain', s: 665, game: 'legendsza', yes: true },
  { t: 'obtain', s: 664, game: 'legendsza', yes: true },
  { t: 'evolve', s: 666, f: 8, from: [665, 0], game: 'legendsza', how: 'Level 12' },
  { t: 'noEvolve', s: 666, f: 1, from: [665, 0], game: 'legendsza' },
  { t: 'evolve', s: 666, f: 1, from: [665, 0], game: 'x', how: 'Level 12' },
  { t: 'obtain', s: 414, game: 'diamond', yes: true },
  // A gender-form species lays eggs of both forms.
  { t: 'obtain', s: 876, f: 1, game: 'sword', yes: true },
  { t: 'obtain', s: 876, game: 'shield', yes: true },
  // Species and form properties.
  { t: 'form', s: 916, genderRate: 4 },
  { t: 'form', s: 678, f: 3, approx: true },
  { t: 'form', s: 678, f: 2, approx: false },
  { t: 'form', s: 555, f: 2, full: 'Galarian Darmanitan' },
  { t: 'form', s: 964, f: 1, full: 'Hero Palafin' },
  { t: 'form', s: 978, f: 1, full: 'Droopy Tatsugiri' },
  { t: 'form', s: 741, f: 1, full: 'Pom-Pom Oricorio' },
  { t: 'row', s: 376, game: 'black', k: 'dream', m: 'Global Link promotion', gender: 2 }
]
